### ISSUE TITLE
res not used in deleteTodo method compile error

### ISSUE THREAD

**Issue by ddetton** [bradtraversy/vue_crash_todolist#15]
After creating the app, I installed the vue router, then installed axios, then copied in these source files.  I got an error in the home.vue file at line 27.  It said that <code>res</code> is not used.  In a comment by Michael Gtz at around 4/30/2020, he said to change the code to look like this:

<code>
deleteTodo(id) {
      axios.delete(`https://jsonplaceholder.typicode.com/todos/${id}`)
        .then(this.todos = this.todos.filter(todo => todo.id !== id))
        .catch(err => console.log(err));
</code>
<br>

and it resolved the error.

**Comment by samarmohan** [comment]
So if it resolved the error, close this issue!
